package stackmd

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/TheJisus28/forge/internal/detect"
)

// Render writes forge/memory/stack.md from a detected stack.
func Render(s detect.Stack) string {
	var b bytes.Buffer
	b.WriteString("# Stack (this repository)\n\n")
	b.WriteString("Agents read this file **before** coding. Do not guess the stack from\n")
	b.WriteString("habit; if this file and the tree disagree, the tree wins and this file\n")
	b.WriteString("should be corrected.\n\n")
	b.WriteString("Generated by `forge init`. Fill in facts by hand.\n\n")
	b.WriteString("```yaml\n")
	b.WriteString("languages:\n")
	if len(s.Languages) == 0 {
		b.WriteString("  []\n")
	} else {
		for _, lang := range s.Languages {
			fmt.Fprintf(&b, "  - %s\n", lang)
		}
	}
	b.WriteString("playbooks:\n")
	if len(s.Playbooks) == 0 {
		b.WriteString("  []\n")
	} else {
		for _, p := range s.Playbooks {
			fmt.Fprintf(&b, "  - %s\n", p)
		}
	}
	fmt.Fprintf(&b, "runtime: %s\n", quote(s.Runtime))
	fmt.Fprintf(&b, "language_version: %s\n", quote(s.LanguageVersion))
	fmt.Fprintf(&b, "build: %s\n", quote(s.Build))
	if s.PackageManager != "" {
		fmt.Fprintf(&b, "package_manager: %s\n", quote(s.PackageManager))
	}
	fmt.Fprintf(&b, "db: \"\"\n")
	fmt.Fprintf(&b, "migrations: \"\"\n")
	fmt.Fprintf(&b, "test: %s\n", quote(s.Test))
	fmt.Fprintf(&b, "dev: %s\n", quote(s.Dev))
	b.WriteString("```\n\n")
	b.WriteString("## Facts\n\n")
	if len(s.Languages) == 0 {
		b.WriteString("No known manifest found (`go.mod`, `package.json`, `build.gradle`,\n")
		b.WriteString("`pom.xml`, …). Fill in the YAML by hand.\n\n")
	} else {
		b.WriteString("What a new agent must know that is not obvious from the tree\n")
		b.WriteString("(HTTP envelope, auth, profiles).\n\n")
	}
	b.WriteString("## Not decided here\n\n")
	b.WriteString("Migrations and features are not announced in the stack.\n")
	return b.String()
}

func quote(s string) string {
	if s == "" {
		return `""`
	}
	if strings.ContainsAny(s, " :#") {
		return fmt.Sprintf("%q", s)
	}
	return s
}
